services:
  docmost:
    build: .
    image: docmost/docmost:latest
    depends_on:
      - redis
    environment:
      APP_URL: 'https://edocs.nguyentracthanh.site'
      APP_SECRET: '75f0dd2daccb8ce094740a8a9af16b8c2f09c6f5981dd1a5ae80ac3a452e9023'
      DATABASE_URL: 'postgresql://cv:cv@postgres:5432/docmost'
      REDIS_URL: 'redis://redis:6379'
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - default
      - traefik_cloudflare
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docmost.rule=Host(`edocs.nguyentracthanh.site`)"
      - "traefik.http.routers.docmost.entrypoints=web"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_cloudflare"

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  docmost:
  redis_data:

networks:
  traefik_cloudflare:
    external: true
